spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.huwagaknjeaimeargczq
    password: 1108qshift0408  # Supabaseで設定したパスワードをここに記述
    driver-class-name: org.postgresql.Driver
    hikari:
<<<<<<< HEAD
      maximum-pool-size: 20
      minimum-idle: 5
=======
      maximum-pool-size: 10
      minimum-idle: 2
>>>>>>> e2089f548ec708cec6e496c0fa3c3e1deda457f7
      connection-timeout: 60000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # 必要に応じて変更
    show-sql: true
    open-in-view: false  # パフォーマンス向上のため false に設定
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    session:
      timeout: 60m  # セッションのタイムアウトを60分に設定
      cookie:
        max-age: 3600  # クッキーの有効期限を3600秒（1時間）に設定

logging:
  level:
    org.hibernate.SQL: DEBUG
<<<<<<< HEAD
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
=======
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

>>>>>>> e2089f548ec708cec6e496c0fa3c3e1deda457f7
